apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000    # Port inside the cluster
      targetPort: 5000  # Port your Flask app runs on inside the container
      nodePort: 30007  # Optional: Expose externally
  type: NodePort  # Use NodePort to access it from localhost
