name: CI/CD for Flask App on KIND

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t nihal009/flask-app:v1 .
          docker push nihal009/flask-app:v1
      - name: Trigger local webhook for Kubernetes redeploy
        run: |
            curl -X POST https://f659-103-89-233-186.ngrok-free.app/webhook
